trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Docker@2
  displayName: Build and push Docker image
  inputs:
    containerRegistry: 'DFEngine Docker Registry'
    repository: 'df-web'
    command: 'buildAndPush'
    Dockerfile: 'config/Dockerfile'
    tags: 'prod'

- task: KubernetesManifest@0
  displayName: Deploy manifest
  inputs:
    action: deploy
    namespace: df-prod
    kubernetesServiceConnection: df-prod-df-engine-aks-df-prod-1571077760081
    manifests: df-web-prod.yml  
    containers: dfengine.azurecr.io/df-web:prod