trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- script: docker build -t dfengine.azurecr.io/df-web:prod -f config/Dockerfile --build-arg NG_ENVIRONMENT=production .
  displayName: Building image

- script: docker login -u dfengine -p $(dockerPassword) dfengine.azurecr.io
  displayName: Login to container registry
        
- script: docker push dfengine.azurecr.io/df-web:prod
  displayName: Pushing image to container registry

- task: KubernetesManifest@0
  displayName: Deploy manifest
  inputs:
    action: deploy
    namespace: df-prod
    kubernetesServiceConnection: df-prod-df-engine-aks-df-prod-1571077760081
    manifests: df-web-prod.yml  
    containers: dfengine.azurecr.io/df-web:prod